name:                lighthouse2048
version:             0.1.0.0
github:              "fwcd/lighthouse-2048"
license:             BSD3
author:              "fwcd"
copyright:           "2022 fwcd"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lighthouse2048#readme>

dependencies:
- base >= 4.7 && < 5
- lighthouse-client

library:
  source-dirs: src

executables:
  lighthouse2048:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lighthouse2048
