resolver: lts-18.23

packages:
- .

extra-deps:
- git: https://github.com/fwcd/lighthouse-haskell.git
  commit: 426db85df0fe0aecd38982aa87eb23688a90ca85
  subdirs:
  - lighthouse-client
- random-1.2.1
- msgpack-1.0.1.0
