resolver: lts-22.13

packages:
- .

extra-deps:
- git: https://github.com/fwcd/lighthouse-haskell.git
  commit: 925956ec6b3a2e8be510a3c07059d27c9fa10506
  subdirs:
  - lighthouse-client
- msgpack-1.0.1.0

# Unfortunately, msgpack still has outdated upper bounds,
# so we will have to ignore those constraints.
allow-newer: true
